In [2]:
import numpy as np
import cvxpy as cp
import matplotlib.pyplot as plt
from scipy.optimize import minimize
import scipy

In [5]:
# data = scipy.io.loadmat('relative_position.mat')
vertices_coords = scipy.io.loadmat('../transforms/vertices.mat')

In [7]:
f = 20e-3
spad_size = 1.6e-3
# spad_board = spad_board.T.reshape(3, 15, 15)
# spad_direction = spad_direction.reshape(3, 1)
# spad_direction = spad_direction / np.sqrt(np.sum(spad_direction ** 2)) * f

In [28]:
points = vertices_coords['points'].T
points[2, :] = 0

In [31]:
def test(spad_info):
    spad_info
    direction_left_top = spad_direction - horizonal + vertical
    direction_left_bottom = spad_direction - horizonal - vertical
    direction_right_top = spad_direction + horizonal + vertical
    direction_right_bottom = spad_direction + horizonal - vertical
    z_distance = spad_location[2]
    focal_points = np.zeros([3, 4])

    # l r r l
    # b b t t
    focal_points[:, 0] = spad_location + (direction_left_bottom / np.abs(direction_left_bottom[2]) * z_distance)
    focal_points[:, 1] = spad_location + (direction_right_bottom / np.abs(direction_right_bottom[2]) * z_distance)
    focal_points[:, 2] = spad_location + (direction_right_top / np.abs(direction_right_top[2]) * z_distance)
    focal_points[:, 3] = spad_location + (direction_left_top / np.abs(direction_left_top[2]) * z_distance)
    # return np.sum(np.square(points - focal_points))/4
    return focal_points

In [38]:
def find_focals(spad_location):
    spad_direction = 
    direction_left_top = spad_direction - horizonal + vertical
    direction_left_bottom = spad_direction - horizonal - vertical
    direction_right_top = spad_direction + horizonal + vertical
    direction_right_bottom = spad_direction + horizonal - vertical
    z_distance = spad_location[2]
    focal_points = np.zeros([3, 4])
    focal_points[:, 0] = spad_location + (direction_left_bottom / np.abs(direction_left_bottom[2]) * z_distance)
    focal_points[:, 1] = spad_location + (direction_right_bottom / np.abs(direction_right_bottom[2]) * z_distance)
    focal_points[:, 2] = spad_location + (direction_right_top / np.abs(direction_right_top[2]) * z_distance)
    focal_points[:, 3] = spad_location + (direction_left_top / np.abs(direction_left_top[2]) * z_distance)
    return np.linalg.norm(points - focal_points)
    # return focal_points

In [60]:
initial_guess = spad_location.copy()
res = minimize(find_focals, initial_guess, method='nelder-mead')

In [61]:
test(res.x)

array([[0.14924459, 0.26200045, 0.25902774, 0.14672739],
       [0.10541368, 0.10406189, 0.20041354, 0.19680028],
       [0.        , 0.        , 0.        , 0.        ]])

In [62]:
res.x

array([-0.44434395,  0.1732491 ,  0.97733474])

In [63]:
galvo_location

array([[-0.75598135,  0.06993698,  0.84848552]])

In [64]:
np.linalg.norm(galvo_location - res.x)

0.35269445667222715